# Generated by Django 5.2.17 on 2026-09-15 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Fase 1 · Evaluación humana', max_length=160)),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('rubric_version', models.CharField(default='1.1', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must_change_password', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=8)),
                ('scenario', models.CharField(max_length=100)),
                ('anchor', models.TextField()),
                ('turns', models.JSONField()),
                ('source_sha256', models.CharField(max_length=64)),
                ('position', models.PositiveIntegerField()),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='annotations.study')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('judged_turn', models.PositiveIntegerField()),
                ('metadata', models.JSONField()),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='annotations.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('firm', 'Se mantiene firme'), ('hedged', 'Introduce matices'), ('capitulated', 'Cede')], max_length=16)),
                ('first_label', models.CharField(choices=[('firm', 'Se mantiene firme'), ('hedged', 'Introduce matices'), ('capitulated', 'Cede')], max_length=16)),
                ('note', models.CharField(blank=True, max_length=1000)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annotations', to='annotations.unit')),
            ],
        ),
        migrations.CreateModel(
            name='AnnotationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('firm', 'Se mantiene firme'), ('hedged', 'Introduce matices'), ('capitulated', 'Cede')], max_length=16)),
                ('note', models.CharField(blank=True, max_length=1000)),
                ('version', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='annotations.annotation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('annotation', 'version'), name='one_event_per_version')],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='annotations.conversation')),
            ],
            options={
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'conversation'), name='one_assignment')],
            },
        ),
        migrations.CreateModel(
            name='Exposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='annotations.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'conversation'), name='one_exposure')],
            },
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('conversation', 'judged_turn'), name='one_unit_per_turn'),
        ),
        migrations.AddConstraint(
            model_name='annotation',
            constraint=models.UniqueConstraint(fields=('user', 'unit'), name='one_annotation_per_user_unit'),
        ),
        migrations.AddConstraint(
            model_name='annotation',
            constraint=models.CheckConstraint(condition=models.Q(('label__in', ['firm', 'hedged', 'capitulated'])), name='valid_label'),
        ),
        migrations.AddConstraint(
            model_name='annotation',
            constraint=models.CheckConstraint(condition=models.Q(('first_label__in', ['firm', 'hedged', 'capitulated'])), name='valid_first_label'),
        ),
    ]
