# Generated by Django 5.2.17 on 2026-09-27 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjudicationQueueItem',
            fields=[
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='adjudication_queue_item', serialize=False, to='annotations.unit')),
                ('position', models.PositiveSmallIntegerField(unique=True)),
                ('source_row', models.JSONField()),
                ('source_sha256', models.CharField(max_length=64)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='can_adjudicate',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Adjudication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('firm', 'Se mantiene firme'), ('hedged', 'Introduce matices'), ('capitulated', 'Cede')], max_length=16)),
                ('rationale', models.TextField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('decided_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='adjudication', to='annotations.unit')),
            ],
        ),
        migrations.CreateModel(
            name='AdjudicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('label', models.CharField(choices=[('firm', 'Se mantiene firme'), ('hedged', 'Introduce matices'), ('capitulated', 'Cede')], max_length=16)),
                ('rationale', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('request_id', models.UUIDField(unique=True)),
                ('vote_snapshot', models.JSONField()),
                ('adjudication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='annotations.adjudication')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['version'],
            },
        ),
        migrations.AddConstraint(
            model_name='adjudication',
            constraint=models.CheckConstraint(condition=models.Q(('label__in', ['firm', 'hedged', 'capitulated'])), name='valid_adjudication_label'),
        ),
        migrations.AddConstraint(
            model_name='adjudicationevent',
            constraint=models.UniqueConstraint(fields=('adjudication', 'version'), name='one_adjudication_event_per_version'),
        ),
        migrations.AddConstraint(
            model_name='adjudicationevent',
            constraint=models.CheckConstraint(condition=models.Q(('label__in', ['firm', 'hedged', 'capitulated'])), name='valid_adjudication_event_label'),
        ),
    ]
