# Generated by Django 5.2.17 on 2026-09-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0002_adjudicationqueueitem_profile_can_adjudicate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjudicationqueueitem',
            name='annotation_state_sha256',
            field=models.CharField(default='', max_length=64),
        ),
    ]
